In [1]:
# changing core directory
import os, sys
dir2 = os.path.abspath('')
dir1 = os.path.dirname(dir2)
if not dir1 in sys.path:
    sys.path.append(dir1)
os.chdir('..')

In [2]:
from src.data import *

In [3]:
dataset_LSTM = load_data('Ford_A_LSTM')
dataset_TS2Vec = load_data('FordA')

X_lstm, y_lstm = dataset_LSTM[0], dataset_LSTM[1] 
X_ts, y_ts = dataset_TS2Vec[0], dataset_TS2Vec[1] 

In [ ]:
X_lstm.shape, y_lstm.shape

((3601, 500), (3601,))

In [5]:
X_ts.shape, y_ts.shape

((3601, 500, 1), (3601,))

In [12]:
X_train, y_train, X_test, y_test = dataset_TS2Vec

# X_train, X_test, y_train, y_test = transform_data(
#         X_train, X_test, y_train, y_test,
#         slice_data = True,
#     )

# y_train

tensor([[0],
        [1],
        [0],
        ...,
        [0],
        [1],
        [0]], dtype=torch.int32)

In [11]:
slice_data = True
window = 50

X_train, y_train, X_test, y_test = dataset_LSTM

# transform from -1, 1 labels to 0, 1. 0,1 saves as 0,1
# y_train = np.array([(int(y)+1) // 2 for y in y_train])
# y_test = np.array([(int(y)+1) // 2 for y in y_test])

np.unique(y_train)
y_train_ = (y_train + 1) // 2
y_test_ = (y_test + 1) // 2

# if slice_data:
#     len_seq = X_train.shape[1]
#     n_patches = len_seq//window

#     X_train = np.vstack([X_train[:, i:i+window] for i in range(n_patches)])
#     X_test = np.vstack([X_test[:, i:i+window] for i in range(n_patches)])

#     y_train = np.concatenate([y_train for _ in range(n_patches)])
#     y_test = np.concatenate([y_test for _ in range(n_patches)])

# X_train.shape, y_train.shape

y_train_, y_train.shape

(array([0, 1, 0, ..., 0, 1, 0]), (3601,))

torch.Size([3601, 1])

In [10]:
np.unique(y_train)

array([-1,  1])